### ISSUE TITLE
Unexpected character encountered while parsing value

### ISSUE THREAD

**Issue by Whitechapel-1888** [Lacro59/playnite-isthereanydeal-plugin#58]
This error pops up whenever updating IsThereAnyDeal data from the extension menu:

`10-02 12:34:21.682|ERROR|IsThereAnyDeal#Common:Error on GetCurrentPrice()|D:\GitHub\Lacro59\playnite-isthereanydeal-plugin\source\Services\IsThereAnyDealApi.cs|645
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Common.Serialization.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 336
   at Playnite.Common.DataSerializer.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 80
   at Playnite.SDK.Data.Serialization.FromJson[T](String json) in C:\projects\playnite\source\PlayniteSDK\Data\DataSerialization.cs:line 406
   at IsThereAnyDeal.Services.IsThereAnyDealApi.GetCurrentPrice(List`1 wishlists, IsThereAnyDealSettings settings) in D:\GitHub\Lacro59\playnite-isthereanydeal-plugin\source\Services\IsThereAnyDealApi.cs:line 645
`

Full logs:
[IsThereAnyDeal_2024-02-10.zip](https://github.com/Lacro59/playnite-isthereanydeal-plugin/files/14229274/IsThereAnyDeal_2024-02-10.zip)

**Comment by Andei** [comment]
Same here
