### ISSUE TITLE
Steam wishlist not showing

### ISSUE THREAD

**Issue by chester681** [Lacro59/playnite-isthereanydeal-plugin#64]
I have just installed this. I am using the epic and steam wishlists. The epic wishlist populates but the steam wishlist doesn't.  I'm using another add on called steam wishlist discount notifier that populates correctly. I've tried disabling that addon to see if it's causing the conflict but the outcome is the same. I have also tried manually inporting the steam wishlist by clicking the link in this plugin's settings but nothing populated.  Is there a log file somewhere I can try to narrow down the issue? Do you have any idea what it might be?

Thanks.

**Comment by PhilosophicalBrit** [comment]
Same issue here!

**Comment by PhilosophicalBrit** [comment]
Seems the last woking version is [ V 3.1](https://github.com/Lacro59/playnite-isthereanydeal-plugin/releases/tag/v3.1)

**Comment by Pyrolyzed** [comment]
Same issue.
However, it can be fixed by downgrading to [v3.1](url) as stated by @PhilosophicalBrit .
### Steps to fix:
1. Download[v3.1's Playnite Extension](url) file
2. Run the file
3. When asked if you would to update the extension, select yes.
4. Optional, open Playnite Settings and navigate to `Updating`, change `Check for add-on updates` to "Only Manually".

This fixes the issue for me, but it's not really a fix, it's a workaround to downgrade the plugin to a older version. An update needs to happen to fix this issue, as I think the Steam wishlist is really the only wishlist the average user will be using.

**Comment by Woffingshire** [comment]
just chiming in to confirm that this issue is still the case. Reverting back to 3.1 fixed the issue

**Comment by riggsmarkham** [comment]
Wanted to chime in and say that this is still failing for me. I'm using GOG, Epic Games, and Steam, and the GOG and Epic Games lists populate properly, but not Steam.
I tried downgrading the version to 3.1, and it was able to pull all the games from Steam as well ... but now it can't get any of the prices for any of the games.

Since Steam is definitely my largest wishlist, I think I'm just going to remove the plugin entirely.

**Comment by vinicius94** [comment]
I can't download wishlist too. I'm attaching the logs to check the problem 
[IsThereAnyDeal_2024-12-07.zip](https://github.com/user-attachments/files/18050045/IsThereAnyDeal_2024-12-07.zip)

**Comment by ciaron88** [comment]
Not working for me too any info if its going to be fixed/updated?

P.S v3.1 also doe not work

**Comment by groove200** [comment]
Same issue here, GOG and EPic working fine, but Steam import seems to have stopped working completely.

**Comment by Lacro59** [comment]
Can you try with this version?
[playnite-isthereanydeal-plugin_3_2_1.zip](https://github.com/user-attachments/files/18684209/playnite-isthereanydeal-plugin_3_2_1.zip)

**Comment by Drknz056** [comment]
App is completely broken for me, can't get it to display anything at all..

**Comment by osmanzeki** [comment]
> Can you try with this version? [playnite-isthereanydeal-plugin_3_2_1.zip](https://github.com/user-attachments/files/18684209/playnite-isthereanydeal-plugin_3_2_1.zip)

Tried it. I can see the view for the extension but it does not display any data. Is there any logs I could look at to help you debug this? When looking at the normal PlayNite log, all I seem to see is that it seems like it is downloading a Steam page's HTML and then it is trying to parse it as if it was JSON. This might be another plugin doing this though so I can't be sure it is related. If I can help debug in any way, let me know and I will do what I can.

Thank you!

**Comment by osmanzeki** [comment]
Actually, I just checked the `extensions.log` file and here is an interesting error that might be related:

```11-02 06:52:17.598|ERROR|IsThereAnyDeal#Common:Error on GetPlain()|D:\GitHub\Lacro59\playnite-isthereanydeal-plugin\source\Services\IsThereAnyDealApi.cs|489
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Playnite.Common.Serialization.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 336
   at Playnite.Common.DataSerializer.FromJson[T](String json) in C:\projects\playnite\source\Playnite\Common\Serialization.cs:line 80
   at Playnite.SDK.Data.Serialization.FromJson[T](String json) in C:\projects\playnite\source\PlayniteSDK\Data\DataSerialization.cs:line 406
   at IsThereAnyDeal.Services.IsThereAnyDealApi.GetPlain(String title, Boolean isSecond) in D:\GitHub\Lacro59\playnite-isthereanydeal-plugin\source\Services\IsThereAnyDealApi.cs:line 489```

**Comment by osmanzeki** [comment]
I noticed while reading the [code](https://github.com/Lacro59/playnite-plugincommon/blob/master/CommonPluginsStores/Steam/SteamApi.cs#L393-L425) that it is indeed downloading the webpage source of the user's Wishlist and [looking for](https://github.com/Lacro59/playnite-plugincommon/blob/master/CommonPluginsShared/Tools.cs#L181-L210) some embedded JSON data inside of it.

I believe this is to avoid having to ask the user to provide an API key but it seems like either Valve changed something to the structure of that page recently or the page changes the embedded JSON depending on some condition for some users (if this bug is not generallized, I'm not sure if everyone is experiencing it or if is a subset of users?).

For users who can provide an API key, the application should be able to talk to the API and receive the appropriate JSON directly by using this endpoint:

### Endpoint
```
https://api.steampowered.com/IWishlistService/GetWishlist/v1/?key=<STEAM_API_KEY>&steamid=<STEAM_USER_ID>&format=json
```

> As documented here: https://steamwebapi.azurewebsites.net/

### Returns
![Image](https://github.com/user-attachments/assets/689b5deb-8b1d-47d2-a5ee-b3fad94a6ef9)

Would it be possible to user the API endpoint instead of trying to find the embedded JSON in the page or would that be too prohibitive for some of the PlayNite users? Having to rely on parsing the webpage or using Regexp will surely break again in the future even if we fix it as Valve might change that page at any time again in the future.

Let me know if I can do anything more to help fix this.

**Comment by osmanzeki** [comment]
As an added note, other wishlist related plugins are also breaking. Possibly due to Steam now requiring 2FA with the Steam Authenticator.

For reference:
https://github.com/darklinkpower/PlayniteExtensionsCollection/issues/471#issuecomment-1873032437

**Comment by Lacro59** [comment]
Thanks for feedback.
Can you try this version?
[playnite-isthereanydeal-plugin_3_2_1.zip](https://github.com/user-attachments/files/18826683/playnite-isthereanydeal-plugin_3_2_1.zip)

**Comment by osmanzeki** [comment]
> Thanks for feedback. Can you try this version? [playnite-isthereanydeal-plugin_3_2_1.zip](https://github.com/user-attachments/files/18826683/playnite-isthereanydeal-plugin_3_2_1.zip)

This seems to be the same version I tried last time. I saw that there are new commits in the repo, is there another version that should be released or did the changes replace the latest version? The latest builds seem to be from 2024 in the Releases list.

**Comment by osmanzeki** [comment]
The release version 3.2.1 seems to be 16 commits behind the `master` branch.

https://github.com/Lacro59/playnite-isthereanydeal-plugin/compare/v3.2.1...master

**Comment by osmanzeki** [comment]
I tried `3.2.1` again, for some reason I do see Giveaway notifications again (those were also broken). Not sure if the latest commits made it to this version or if something else change. I still cannot load the contents of the ITAD tab in PlayNite that said.

**Comment by osmanzeki** [comment]
Wait! Can confirm it works all of a sudden. So strange:

![Image](https://github.com/user-attachments/assets/8773526d-2c15-4ab0-985e-7e77ee48cf5f)

**Comment by osmanzeki** [comment]
It seems like the plugin was able to download the `Steam.json` file from the page and save it. When it is able to load this file, it is able to display the contents in the ITAD tab. I tried adding a new game (that is on sale) to my wishlist and reload the data and it seems to be stuck on the `Downloading...` state now.

**Comment by groove200** [comment]
> Thanks for feedback. Can you try this version? [playnite-isthereanydeal-plugin_3_2_1.zip](https://github.com/user-attachments/files/18826683/playnite-isthereanydeal-plugin_3_2_1.zip)

This version is working for me :-)
